# Generated by Django 5.0.2 on 2024-02-16 15:41

from django.db import migrations
from itertools import product

def create_groups(apps, schema_migration):
    User = apps.get_model('user', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    actions = ['add', 'view', 'change', 'delete']

    models = [
        'recipe',
        'ingredient',
        'utensil',
        'step',
        'comment',
        'tag',
        'recipeingredientrelationship'
    ]

    permissions = {
        f"{action}_{model}": Permission.objects.get(codename=f"{action}_{model}") for (action, model) in product(actions, models)
    }
    
    colocataires_permissions = [permissions[key] for key in permissions.keys()]
    
    colocataires = Group(name='colocataires')
    colocataires.save()
    colocataires.permissions.set(colocataires_permissions)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
